In [2]:
# Exercise 1

In [3]:
a, b = (list(range(0, int(1e7) - 1)) for i in range(2))

In [4]:
def add_with_for(a, b):
     c = []
     for i in range(0, len(a)):
        c.append(a[i] + b[i])
     return c

In [5]:
add_with_for(a, b)

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [6]:
import numpy as np

In [7]:
np.add(np.arange(1e7-1), np.arange(1e7-1))

array([0.0000000e+00, 2.0000000e+00, 4.0000000e+00, ..., 1.9999992e+07,
       1.9999994e+07, 1.9999996e+07])

In [8]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
np.tile([0.,1.], 50).reshape(10,10)

array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [10]:
c = np.concatenate([[0.], np.repeat(1., 10)])
d = np.append(np.tile(c, 9), 0.).reshape(10,10)
d

array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [11]:
e = np.flip(d, 1)

In [12]:
np.linalg.det(d.dot(e))

-81.0000000000001

In [13]:
np.linalg.det(d) * np.linalg.det(e)

-81.0

In [14]:
from sklearn.datasets import load_boston
import pandas as pd
boston = load_boston()
boston.data.shape

(506, 13)

In [15]:
df = pd.DataFrame(boston.data, columns=boston.feature_names)

In [16]:
df.loc[df['CRIM'] > 1]

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
16   1.05393  0.0   8.14   0.0  0.538  5.935  29.3  4.4986   4.0  307.0   
20   1.25179  0.0   8.14   0.0  0.538  5.570  98.1  3.7979   4.0  307.0   
22   1.23247  0.0   8.14   0.0  0.538  6.142  91.7  3.9769   4.0  307.0   
29   1.00245  0.0   8.14   0.0  0.538  6.674  87.3  4.2390   4.0  307.0   
30   1.13081  0.0   8.14   0.0  0.538  5.713  94.1  4.2330   4.0  307.0   
..       ...  ...    ...   ...    ...    ...   ...     ...   ...    ...   
483  2.81838  0.0  18.10   0.0  0.532  5.762  40.3  4.0983  24.0  666.0   
484  2.37857  0.0  18.10   0.0  0.583  5.871  41.9  3.7240  24.0  666.0   
485  3.67367  0.0  18.10   0.0  0.583  6.312  51.9  3.9917  24.0  666.0   
486  5.69175  0.0  18.10   0.0  0.583  6.114  79.8  3.5459  24.0  666.0   
487  4.83567  0.0  18.10   0.0  0.583  5.905  53.2  3.1523  24.0  666.0   

     PTRATIO       B  LSTAT  
16      21.0  386.85   6.58  
20      21.0  376.57  21.02  
22      21.0  396.90  18.72  
29      21.0  380.23  11.98  
30      21.0  360.17  22.60  
..       ...     ...    ...  
483     20.2  392.92  10.42  
484     20.2  370.73  13.34  
485     20.2  388.62  10.58  
486     20.2  392.68  14.98  
487     20.2  388.22  11.45  

[174 rows x 13 columns]

In [17]:
df.loc[(df['PTRATIO'] > 16) & (df['PTRATIO'] < 18)]

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE      DIS  RAD    TAX  \
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9   4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1   4.9671  2.0  242.0   
41   0.12744   0.0   6.91   0.0  0.448  6.770   2.9   5.7209  3.0  233.0   
42   0.14150   0.0   6.91   0.0  0.448  6.169   6.6   5.7209  3.0  233.0   
43   0.15936   0.0   6.91   0.0  0.448  6.211   6.5   5.7209  3.0  233.0   
..       ...   ...    ...   ...    ...    ...   ...      ...  ...    ...   
343  0.02543  55.0   3.78   0.0  0.484  6.696  56.4   5.7321  5.0  370.0   
344  0.03049  55.0   3.78   0.0  0.484  6.874  28.1   6.4654  5.0  370.0   
347  0.01870  85.0   4.15   0.0  0.429  6.516  27.7   8.5353  4.0  351.0   
348  0.01501  80.0   2.01   0.0  0.435  6.635  29.7   8.3440  4.0  280.0   
353  0.01709  90.0   2.02   0.0  0.410  6.728  36.1  12.1265  5.0  187.0   

     PTRATIO       B  LSTAT  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
41      17.9  385.41   4.84  
42      17.9  383.37   5.81  
43      17.9  394.46   7.44  
..       ...     ...    ...  
343     17.6  396.90   7.18  
344     17.6  387.97   4.61  
347     17.9  392.43   6.36  
348     17.0  390.94   5.99  
353     17.0  384.46   4.50  

[100 rows x 13 columns]

In [18]:
df['MEDV'] = boston.target
df.loc[df['MEDV'] > 25]['NOX'].mean()

0.4921201612903226

In [19]:
# Exercise 2

In [20]:
import os
os.getcwd()

'/home/xbexbex/git/ids/week1'

In [21]:
automotive = pd.read_json('reviews_Automotive_5.json', lines=True)
automotive

reviewerID        asin                        reviewerName  \
0      A3F73SC1LY51OO  B00002243X                     Alan Montgomery   
1      A20S66SKYXULG2  B00002243X                            alphonse   
2      A2I8LFSN2IS5EO  B00002243X                               Chris   
3      A3GT2EWQSO45ZG  B00002243X                              DeusEx   
4      A3ESWJPAVRPWB4  B00002243X                        E. Hernandez   
...               ...         ...                                 ...   
20468  A1KB43BI085A48  B00KIAQ8VW                             Mike F.   
20469  A3HIUWKL4D853W  B00KIAQ8VW                                RayH   
20470  A1S95WASXJ02VX  B00KIAQ8VW                 Roberto Aguilar Jr.   
20471  A2IID0Z6EHF5KP  B00KIAQ8VW                              Soarer   
20472  A3HKZTFCPIK2OE  B00KIAQ8VW  SSG Barnes (ABN) "James C. Barnes"   

        helpful                                         reviewText  overall  \
0        [4, 4]  I needed a set of jumper cables for my new car...        5   
1        [1, 1]  These long cables work fine for my truck, but ...        4   
2        [0, 0]  Can't comment much on these since they have no...        5   
3      [19, 19]  I absolutley love Amazon!!!  For the price of ...        5   
4        [0, 0]  I purchased the 12' feet long cable set and th...        5   
...         ...                                                ...      ...   
20468    [1, 1]  I've bought 10 of these over the past year to ...        5   
20469    [0, 0]  OK, I have to admit, the price of this item di...        2   
20470    [0, 0]  I love my skull face mask. It makes me outstan...        5   
20471    [0, 0]  This mask of course as described is half-face ...        5   
20472    [0, 0]  Good light weight for just cool nights or rain...        5   

                                                 summary  unixReviewTime  \
0             Work Well - Should Have Bought Longer Ones      1313539200   
1                                       Okay long cables      1315094400   
2                             Looks and feels heavy Duty      1374710400   
3                  Excellent choice for Jumper Cables!!!      1292889600   
4                 Excellent, High Quality Starter Cables      1341360000   
...                                                  ...             ...   
20468                    Excellent quality for the price      1396915200   
20469  Light weight neck and face cover with whimsica...      1391472000   
20470            I love to ride with my Skull Face Mask.      1386547200   
20471                              Great neck protection      1357171200   
20472                                          FACE MASK      1395100800   

        reviewTime  
0      08 17, 2011  
1       09 4, 2011  
2      07 25, 2013  
3      12 21, 2010  
4       07 4, 2012  
...            ...  
20468   04 8, 2014  
20469   02 4, 2014  
20470   12 9, 2013  
20471   01 3, 2013  
20472  03 18, 2014  

[20473 rows x 9 columns]

In [55]:
stop_words=pd.read_csv('stop-word-list.csv', sep=',',header=None)

if "the" in stop_words.values[0]:
    print("asdf")

if 2 in [1,2,3]:
    print("vittu")

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan])

In [23]:
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: x.lower())

In [24]:
import re

In [25]:
punctuation = r'[!"#\$\%\&\\\'\(\)\*\+\,-./:;<=>?@\[\]^_`\{|\}~]'

In [26]:
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: re.sub(punctuation, '', x))

In [34]:
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

In [28]:
import nltk
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.porter import PorterStemmer

In [29]:
snowball_stemmer = SnowballStemmer('english')
porter_stemmer = PorterStemmer()

In [30]:
automotive['reviewText'] = automotive['reviewText'].apply(lambda x: ' '.join([snowball_stemmer.stem(porter_stemmer.stem(word)) for word in x.split()]))

In [31]:
automotive['reviewText']

0        i need a set of jumper cabl for my new car and...
1        these long cabl work fine for my truck but the...
2        cant comment much on these sinc they have not ...
3        i absolutley love amazon for the price of a se...
4        i purcha the 12 feet long cabl set and they ar...
                               ...                        
20468    ive bought 10 of these over the past year to g...
20469    ok i have to admit the price of thi item did n...
20470    i love my skull face mask it make me outstand ...
20471    thi mask of cour as describ is halffac but wit...
20472    good light weight for just cool night or rain ...
Name: reviewText, Length: 20473, dtype: object

In [32]:
pos = automotive.loc[automotive['overall'] >= 4]['reviewText']
pos.to_csv(r'pos.txt', header=False, index=None, mode='a', sep=' ')

In [33]:
neg = automotive.loc[automotive['overall'] <= 2]['reviewText']
neg.to_csv(r'neg.txt', header=False, index=None, mode='a', sep=' ')